### ISSUE TITLE
The me parameter should not be described as “originally entered”.

### ISSUE THREAD

**Issue by Zegnat** [indieweb/indieauth#11]
In the different sections on requests, the `me` parameter is described as:

> The profile URL that the user entered

and:

> The user's profile URL as originally entered

I don’t think this is ever right. After the client has done URL Canonicalization on the user input, and followed redirects during Discovery by Clients to possibly update the URL, the final product should be used. This can be very different from whatever the user has actually entered.

**Comment by aaronpk** [comment]
Good catch!

I've changed the first one to "The user's profile URL", and the second one to "The user's profile URL as originally used in the authorization request"
