### ISSUE TITLE
Client Information Discovery without relying on microformats parsers.

### ISSUE THREAD

**Issue by Zegnat** [indieweb/indieauth#23]
This issue was created in response to [a discussion in #indieweb-dev](https://chat.indieweb.org/dev/2018-08-19). The essentials should be summarised here, but for full context, see the chat logs [starting at 11:31](https://chat.indieweb.org/dev/2018-08-19#t1534678280193900), ending [around 11:55](https://chat.indieweb.org/dev/2018-08-19#t1534679742798000).

---

@pfefferle asked if it were possible to use a separate parser just for extracting [`h-app`](http://microformats.org/wiki/h-app) ([IndieWeb wiki](https://indieweb.org/h-app)) information. Because for such “a very simple and uncomplicated format <i>[…]</i> it would be a bit too much to include the mf2 parser”.

The problem with a boiled down parser is it would be making assumption with regards to how the author is adding the `h-app` object to a page. And as soon as more complex microformats structures (nesting, implied values, vcp) are introduced to the mix anything that is not a full mf2 parser will likely fail.

Conversely there might be reasons why shipping a full mf2 parser with every authorization endpoint is a problem. These problems can range from unavailability of a parser in a language, to more specific issues with packaging. The latter is what is happening for WordPress. Multiple plugins all have to ship their own version of the parser, fighting with each other over which one gets used, because there is no concept of shared dependencies.

The IndieAuth specification only depends on microformats for extracting [application information](https://indieauth.spec.indieweb.org/#application-information) during [client information discovery](https://indieauth.spec.indieweb.org/#client-information-discovery). If this could be changed or offer an alternative straight from the HTML without further dependencies that might help authorization servers in doing this discovery.

(Note that the [discovery of redirect urls](https://indieauth.spec.indieweb.org/#redirect-url) already depends on HTML parsing for finding `<link>` elements, so depending on HTML parsing for other client information should be fine.)

Some possible alternatives mentioned during the discussion:

* [Open Graph](http://ogp.me/) – embed the application meta data in `<meta>` elements. As there is no application [type](http://ogp.me/#types), this may require defining a new namespace.
* HTML – use standard HTML elements and relationships. `rel="icon"` for the logo, `rel="self"` for the `client_id`. The application name could be extracted from `<title>` or more specific [`<meta name="application-name">`](https://html.spec.whatwg.org/multipage/semantics.html#meta-application-name) elements.
* [Web App Manifest](https://www.w3.org/TR/appmanifest/) – a JSON encoded [sidefile](https://indieweb.org/sidefile-antipattern) containing all the necessary meta data. This will require discovery of the manifest file, and then a second HTTP request to retrieve it. Once retrieved the parsing is extremely straight-forward.
* [JSON-LD](https://json-ld.org/) – if a strictly specified subset is used it could be parsed with any JSON parser (no need for full JSON-LD parsing) and can be [embedded within HTML](https://www.w3.org/TR/json-ld/#embedding-json-ld-in-html-documents) (`<script type="application/ld+json">…</script>`).

**Comment by Zegnat** [comment]
I have started some [initial documentation](https://indieweb.org/User:Vanderven.se_martijn/IndieAuth_Client_Information) to see exactly what applications are publishing for discovery. [Current statistics](https://indieweb.org/wiki/index.php?title=User:Vanderven.se_martijn/IndieAuth_Client_Information&oldid=51122):

| h-app | h-x-app | rel=redirect_uri |
| --- | --- | --- |
| 10% (2/20) | 25% (5/20) | 10% (2/20) |

Next it would be helpful to see what other meta data points these pages are publishing, and have in common. Things I want to check:

* `rel="manifest"` existence
* `rel="icon"` existence (alternatively Apple touch icons)

Please help expand [that wiki page](https://indieweb.org/User:Vanderven.se_martijn/IndieAuth_Client_Information) with any further ideas!

**Comment by Zegnat** [comment]
The table above has been updated with new statistics. This shows that `rel="manifest"` are equally as likely to be found on client pages as `h-x-app`. This Web App Manifests may be a more logical alternative than previously realised.

Further developments in mostly chronological order, for those who do not want to read a day’s worth of chat logs:

* @dshanske is [reports](https://chat.indieweb.org/dev/2018-08-19/1534697620548000) looking for other ways to discover application logos.
  
  * This will [likely](https://chat.indieweb.org/dev/2018-08-19/1534698316473300) be based on [the wiki documentation on home page icons](https://indieweb.org/icon).
  
* @aaronpk [provides another reason](https://chat.indieweb.org/dev/2018-08-19#t1534697632659200) why `h-app` (and the microformats2 parser requirements it brings along) may not align with IndieAuth, as it relates to his future goal of the spec:
  
  * > my next goal with IndieAuth is to get just the client ID part written up as an i-d and proposed to the OAuth WG
  * > and I’m a bit apprehensive of including microformats parsing in that proposal

* @kevinmarks [proposes native HTML fallbacks](https://chat.indieweb.org/dev/2018-08-19#t1534697766347500) for the `h-app` properties:
  
  * > url: fall back to <i>[the page’s]</i> url
    
  * > logo: fall back to icons
    
    * The problem with this is also pointed out: [which icon?](https://chat.indieweb.org/dev/2018-08-19/1534697822459600) Icons can mean many things, from the default `rel="icon"` to a slew of `rel="apple-touch-icon-*"`, [and more](https://github.com/audreyr/favicon-cheat-sheet).
    
  * > name: fall back to <title> or other metadata
    
    * Another problem is raised: [`<title>` elements are often filled with more than just a name](https://chat.indieweb.org/dev/2018-08-19/1534697862981600). This problem was [already pointed out](https://chat.indieweb.org/dev/2018-08-19/1534679187741900) in the original discussion this morning.
  
* @tantek points out that [localisation of client names](https://chat.indieweb.org/dev/2018-08-19/1534698458933500) might be important. This is something explicitly covered by `<meta name="application-name">` elements, but not available to current `h-app` implementations.
  
* @EdwardHinkle gives another voice to the client implementers and [comments on the friction](https://chat.indieweb.org/dev/2018-08-19#t1534700314240800) added by reading `h-app`:
  
  * > <i>[…]</i> while I’ve found Microformats to be extremely helpful in many cases, mf2 in the IndieAuth process is the biggest friction I’ve ever found. I wouldn’t be opposed to there being a different way to find client info from a url
    
  * > Easy to add mf2 to an app’s page. But when writing IndieAuth client code, you either have to add an mf2 library just for that one step or roll your own just for the h-app stage which typically ends up buggy
  
  * @Zegnat [adds](https://chat.indieweb.org/dev/2018-08-19/1534703895251300) that the manifest file would also be easy enough to implement in selfauth, and would get his preference over bringing an mf2 parser.
  
* @tantek [wonders if Web App Manifest is the answer](https://chat.indieweb.org/dev/2018-08-19/1534700709865800) and asks for implementer feedback.
  
  * @aaronpk points out that [it requires an extra HTTP request](https://chat.indieweb.org/dev/2018-08-19/1534700734362600), but also that [the extra HTTP request may be preferred over running an mf2 parser](https://chat.indieweb.org/dev/2018-08-19/1534700825303000).
  
  * @EdwardHinkle notes that the JSON offered by the WAM will be [much easier](https://chat.indieweb.org/dev/2018-08-19/1534700855544400), also [in the context of an authorization endpoint](https://chat.indieweb.org/dev/2018-08-19/1534700970543000).
  
  * @sknebel [wonders](https://chat.indieweb.org/dev/2018-08-19/1534700982297900) if it is “weird to use <i>[WAM]</i> for non-web-apps”.
  
  * @aaronpk is [concerned](https://chat.indieweb.org/dev/2018-08-19/1534701043711800) about the effects of publishing a WAM for a page that isn’t itself a web application, but rather just an information page about an external (sometimes web) application.
    
    * @sknebel [points out](https://chat.indieweb.org/dev/2018-08-19/1534701179179200) that there are multiple [“installability signals”](https://www.w3.org/TR/appmanifest/#installability-signals) and that it is unlikely such a minimal manifest file will trigger unwanted behaviour.
    
    * @EdwardHinkle [publishes a minimal WAM](https://chat.indieweb.org/dev/2018-08-19#t1534702022354300) for [Indigenous for iOS](https://indigenous.abode.pub/ios/) at [`manifest.webmanifest`](https://indigenous.abode.pub/ios/manifest.webmanifest) for testing. Nobody notices any unwanted side-effects.
  
* @EdwardHinkle points out that [the manifest file can also help advertise the actual application](https://chat.indieweb.org/dev/2018-08-19/1534702248281200):
  
  * > I put in name, icons, prefer_related_applications and related_applications. The last two aren’t required obviously, but helpful if browsers decide to use that to prompt for App Store links.

From the discussions had it seems like everyone is having a positive outlook on Web App Manifest as a place to find application meta-data.

**Comment by EdwardHinkle** [comment]
<img width="592" alt="screen shot 2018-08-21 at 11 39 24 am" src="https://user-images.githubusercontent.com/786014/44412511-1e9a1980-a537-11e8-8777-c60aad35867f.png">

Display Together's Client Info using WAM

**Comment by Zegnat** [comment]
The survey has been updated to tally how many client pages are advertising logos in the form of `rel="icon"`, `rel="apple-touch-icon"`, and `rel="mask-icon"` links, as extracted by a microformats parser.

Both `rel="icon"` and `rel="apple-touch-icon"` have wide support across pages.

**Comment by capjamesg** [comment]
In the context of IndieAuth itself, has there been any more recent implementer feedback to suggest h-x-app may not be appropriate for client discovery? I find the solution quite elegant in its markup -- providing just what a client needs -- but I understand the low adoption and the need for a microformats parser need to be considered.

**Comment by dshanske** [comment]
Should we close this in favor of #133 ?

**Comment by Zegnat** [comment]
As creator of this issue, I am not opposed. I think a client metadata document and a way to discover it is a perfectly valid alternative to parsing microformats. And probably much better than any of the other side-file ideas offered herein.

Let’s give people some time to oppose, and if nothing, close this issue in a couple days?

**Comment by capjamesg** [comment]
I am in agreement with @Zegnat's position.

**Comment by dshanske** [comment]
So am I.. Just wanted to get the discussion started.

**Comment by aaronpk** [comment]
Great, sounds like we generally have support for this. I merged in #138 so I'll close this now.
