### ISSUE TITLE
Align/adopt RFC7662 token introspection and `active: true`

### ISSUE THREAD

**Issue by jamietanna** [indieweb/indieauth#33]
Just having a re-read through the access token introspection sections on the [IndieAuth spec](https://indieauth.spec.indieweb.org/#access-token-verification) compared to [OAuth2](https://tools.ietf.org/html/rfc7662), and I noticed that IndieAuth doesn't provide the `active: true` field in the response, and I wondered what the thought behind that was.

Would having it as a requirement in IndieAuth also allow interactions via existing OAuth2 libraries / with minimal changes?

**Comment by Zegnat** [comment]
IndieAuth doesn’t really do any of the [OAuth 2.0 Token Introspection](https://tools.ietf.org/html/rfc7662) (RFC 7662) interactions. I don’t think the token validation in IndieAuth is based on that at all, actually, though @aaronpk is the only one qualified to comment on that.

A huge difference that jumps out is that RFC 7662 requires you to `POST` the token you are interested in to the endpoint. Another big one is that it requires additional authentication along with the token to see whether the current requester is allowed to check a token in the first place. IndieAuth does not concern itself with either of those things.

I’d say the token endpoint in IndieAuth considers itself to also be a protected resource. When you supply a correct bearer token, the resource is returned, and that resource happens to be a JSON encoding of the data linked to your token. In my mind I compare it to being logged in to a website and viewing your own profile. You are logged in (ie. sending the bearer token) and are requesting your profile (the `me` associated with your session).

All that said, I do wonder if there is some argument to be made for swapping IndieAuth’s [Access Token Verification](https://indieauth.spec.indieweb.org/#access-token-verification) for something closer to RFC 7662. Or maybe even just a small extension on RFC 7662 like how revocation is handled as an extension of RFC 7009…

**Comment by jamietanna** [comment]
I have added the <code>active</code> path into the token verify response, as part of [my new IndieAuth server](https://www.jvt.me/posts/2020/12/09/personal-indieauth-server/), as well as adding support for an RFC7662 token introspection endpoint, too

(Originally published at: https://www.jvt.me/mf2/2020/12/n8ue5/)

**Comment by aaronpk** [comment]
* Modify [access token verification](https://indieauth.spec.indieweb.org/#access-token-verification) section to extend [Token Introspection Response](https://datatracker.ietf.org/doc/html/rfc7662#section-2.2) to include:
  * The introspection endpoint is the same as the token endpoint.
  * The introspection response includes an additional parameter `me`
* In the introspection section, mention other properties that must/should be returned:
  * `active`, `exp`, `iat`

**Comment by dshanske** [comment]
Just to note, the GET response returns a 400, 401, or 403 respons eto an invalid token. the introspection endpoint change would require a 200 with active: false.
