### ISSUE TITLE
Consider using OAuth Server Metadata

### ISSUE THREAD

**Issue by aaronpk** [indieweb/indieauth#43]
Currently IndieAuth clients discover two pieces of information from the user's profile page, the authorization endpoint and token endpoint. As we continue to expand IndieAuth into new use cases (such as automated indieauth between two machines acting on behalf of users), we may need to include additional information to clients.

If IndieAuth 1.1 is not backwards compatible with IndieAuth, (such as if PAR is a requirement), clients will need to know which version is supported in order to know how to behave, and that means either adding another link tag or changing the names of the rel values.

There is an OAuth extension which talks about how to communicate information about an OAuth server to clients by publishing a JSON document at the metadata URL for the server.

We could instead have the IndieAuth client look for just one value in the HTML, the metadata endpoint, and have the client fetch everything else from there. While this does add an HTTP request in the initial setup compared to the current state, it may end up being preferable longer term. (PAR ends up adding a request in the setup too anyway.)

A straw proposal for how this could work is:

* Client fetches the user's entered profile URL and looks for `<link rel="indieauth_metadata" href="https://indieauth.example.com/metadata.json">` (the filename does not need to be standardized since it's discoverable from this link)
* Client parses that document looking for the properties `authorization_endpoint` and `token_endpoint`
* Client sends a pushed authorization request to the authorization endpoint, then redirects the browser to the resulting URL
* ... continue as normal

**Comment by pfefferle** [comment]
If the new version of IndieAuth is not backwards compatible, I would vote for a major change of the version number and call it 2.0 (https://semver.org/).

**Comment by jamietanna** [comment]
Is this expected to be similar to [OpenID Connect Discovery](https://openid.net/specs/openid-connect-discovery-1_0.html)?

What sort of properties are we thinking would be provided?

I would guess:

- `authorization_endpoint`
- `grant_types_supported`
- `response_types_supported`
- `scopes_supported`
- `token_endpoint`

But is there anything specific we'd want for IndieAuth? Maybe something like whether we support #40?

**Comment by manton** [comment]
I don't know enough yet to comment on whether this is needed, but if it is, what about simply `rel="indieauth"`, without the "_metadata"? That seems more consistent with "micropub", "microsub", and "webmention".

**Comment by aaronpk** [comment]
Technically once you add all the OAuth 2.0 extensions on top, OAuth 2.0 isn't even backwards compatible with itself. But in any case, the name isn't super relevant to this discussion.

The extension point from OAuth is [RFC8414](https://tools.ietf.org/html/rfc8414). The two main ones needed are `authorization_endpoint` and `token_endpoint`, I could see `scopes_supported` potentially being useful too. In general I'd want to leave out as much as possible unless there's a clear reason to add it.

`rel="indieauth"` could work, I guess I suggested `indieauth_metadata` first because this URL isn't the indieauth server itself, it's a document describing the server. But in any case it's more important to decide whether this is even a good idea than what it's called right now.

**Comment by aaronpk** [comment]
Removing this from the GitHub milestone for now while we focus on the current open issues we discussed at the popup.

**Comment by aaronpk** [comment]
Note that in #17 we shouldn't use underscores in HTTP headers. 

`rel=indieauth-metadata`

**Comment by jamietanna** [comment]
Closing, as this is now adopted by #102.
