### ISSUE TITLE
Document changelog that grant_type is now required

### ISSUE THREAD

**Issue by dshanske** [indieweb/indieauth#61]
In the current living standard, grant_type is required by the authorization endpoint. In the prior version, it was not. This change needs to be documented due the fact it could be a breaking change.

**Comment by Zegnat** [comment]
I think this is wrong?

Maybe I am missing something, but I think `grant_type` has always been required. It was `response_type` that was optional (in the case of `response_type=id`) and that has been documented as part of the [August 9th changes](https://indieauth.spec.indieweb.org/#changes-from-25-january-2020-to-09-august-2020).

Am I misreading something?

**Comment by dshanske** [comment]
@Zegnat For the token endpoint, but not the authorization endpoint.

**Comment by Zegnat** [comment]
Ah, found it now @dshanske. Thanks! PR opened with fix.
